/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Won_WinDesktop;

import java.io.File;

/**
 *
 * @author Minhawn
 */
public class int_driveframe extends javax.swing.JInternalFrame {

    /**
     * Creates new form int_driveframe
     */
    
    File file;
    File[] list_files;
    String outputfiles;
    String filename;
    
    
    public int_driveframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        drive_dir_list = new javax.swing.JTextArea();
        drive_search_button = new javax.swing.JButton();
        drive_search_text = new javax.swing.JTextField();
        drive_go_button = new javax.swing.JButton();
        drive_dir_text = new javax.swing.JTextField();
        case_sensitve_box = new javax.swing.JCheckBox();
        delete_box = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("File Explorer");
        setVisible(true);

        drive_dir_list.setEditable(false);
        drive_dir_list.setBackground(new java.awt.Color(0, 0, 0));
        drive_dir_list.setColumns(20);
        drive_dir_list.setForeground(new java.awt.Color(0, 155, 0));
        drive_dir_list.setLineWrap(true);
        drive_dir_list.setRows(5);
        jScrollPane1.setViewportView(drive_dir_list);

        drive_search_button.setBackground(new java.awt.Color(204, 204, 204));
        drive_search_button.setText("Search");
        drive_search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drive_search_buttonActionPerformed(evt);
            }
        });

        drive_search_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drive_search_textActionPerformed(evt);
            }
        });

        drive_go_button.setBackground(new java.awt.Color(204, 204, 204));
        drive_go_button.setText("Select");
        drive_go_button.setRequestFocusEnabled(false);
        drive_go_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drive_go_buttonActionPerformed(evt);
            }
        });

        drive_dir_text.setText("C:/");

        case_sensitve_box.setSelected(true);
        case_sensitve_box.setText("Case Sensitive");

        delete_box.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(delete_box)
                        .addGap(100, 100, 100)
                        .addComponent(drive_go_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(159, 159, 159))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(case_sensitve_box)
                        .addGap(60, 60, 60)
                        .addComponent(drive_search_button, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                        .addGap(159, 159, 159))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(drive_dir_text)
                            .addComponent(drive_search_text, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(drive_dir_text, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drive_go_button, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(delete_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drive_search_text, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drive_search_button, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(case_sensitve_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void drive_go_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drive_go_buttonActionPerformed

        try
        {
        file = new File(drive_dir_text.getText());
        
        if(delete_box.isSelected())
        {
            try
        {
            drive_dir_list.setText((drive_dir_text.getText()) + "has been deleted");
            file.delete();
        }
        catch(Exception ex)
        {
        drive_dir_list.setText("Error in deleting file");
      
        }
        }
        
        else{
        list_files = file.listFiles();
        
        for(int i = 0; i < list_files.length; i++)
        {
            outputfiles += (list_files[i].getName()) + "\n";
        }
        
        
        
        drive_dir_list.setText(outputfiles);
        outputfiles = "";}
        }
        
        catch(Exception ex)
        {
            outputfiles = "Error!";
        }
        
        

    }//GEN-LAST:event_drive_go_buttonActionPerformed

    private void drive_search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drive_search_buttonActionPerformed
            file = new File(drive_dir_text.getText());
            list_files = file.listFiles();
            for(int i = 0; i < list_files.length; i++)
            {
                filename = (list_files[i].getName());
                
                
                if(case_sensitve_box.isSelected())
                {
                if(filename.contains(drive_search_text.getText()))
                {
                    outputfiles += filename + "\n";
                }}
                
                else
                {
                    
                if(filename.toLowerCase().contains(drive_search_text.getText().toLowerCase()))
                {
                    outputfiles += filename + "\n";
                }
                
                }
                
            }
            drive_dir_list.setText(outputfiles);
            outputfiles = "";

    }//GEN-LAST:event_drive_search_buttonActionPerformed

    private void drive_search_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drive_search_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drive_search_textActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox case_sensitve_box;
    private javax.swing.JCheckBox delete_box;
    private javax.swing.JTextArea drive_dir_list;
    private javax.swing.JTextField drive_dir_text;
    private javax.swing.JButton drive_go_button;
    private javax.swing.JButton drive_search_button;
    private javax.swing.JTextField drive_search_text;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
