/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Won_WinDesktop;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.LayoutManager2;
import java.awt.Panel;

/**
 *
 * @author Minhawn
 */
public class int_rgbframe extends javax.swing.JInternalFrame {

    /**
     * Creates new form 
     */
    public int_rgbframe() {
        initComponents();
        init();
    }
    BorderLayout lay1;
    
    GridLayout lay2;
    java.awt.LayoutManager2 lm;
    java.awt.LayoutManager2 lm2;

    Panel p = new Panel(new BorderLayout());

    public void init()
    {
        lm=(LayoutManager2) this.getContentPane().getLayout();
        lm2=(LayoutManager2)panel_reserve.getLayout();
        
        lay1=new BorderLayout();
        lay2=new GridLayout(2,2);
        
        lay1.addLayoutComponent(panel1, BorderLayout.NORTH);
        lay1.addLayoutComponent(panel2, BorderLayout.WEST);
        lay1.addLayoutComponent(center_panel, BorderLayout.EAST);
        lay1.addLayoutComponent(button_panel, BorderLayout.SOUTH);
        
        lay1.addLayoutComponent(panel_reserve, BorderLayout.CENTER);   
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        panel1r = new javax.swing.JTextField();
        panel_txt1 = new javax.swing.JLabel();
        panelg1 = new javax.swing.JTextField();
        panelb1 = new javax.swing.JTextField();
        panel2 = new javax.swing.JPanel();
        panel2r = new javax.swing.JTextField();
        panel_txt2 = new javax.swing.JLabel();
        panelg2 = new javax.swing.JTextField();
        panelb2 = new javax.swing.JTextField();
        center_panel = new javax.swing.JPanel();
        status = new javax.swing.JTextField();
        status_txt = new javax.swing.JLabel();
        button_panel = new javax.swing.JPanel();
        format1_button = new javax.swing.JButton();
        default_button = new javax.swing.JButton();
        panel_reserve = new javax.swing.JPanel();
        panel4 = new javax.swing.JPanel();
        panel4r = new javax.swing.JTextField();
        panel_txt4 = new javax.swing.JLabel();
        panelg4 = new javax.swing.JTextField();
        panelb4 = new javax.swing.JTextField();
        panel5 = new javax.swing.JPanel();
        panel5r = new javax.swing.JTextField();
        panel_txt5 = new javax.swing.JLabel();
        panelg5 = new javax.swing.JTextField();
        panelb5 = new javax.swing.JTextField();
        panel7 = new javax.swing.JPanel();
        panel7r = new javax.swing.JTextField();
        panel_txt7 = new javax.swing.JLabel();
        panelg7 = new javax.swing.JTextField();
        panelb7 = new javax.swing.JTextField();
        panel8 = new javax.swing.JPanel();
        panel8r = new javax.swing.JTextField();
        panel_txt8 = new javax.swing.JLabel();
        panelg8 = new javax.swing.JTextField();
        panelb8 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 128, 128));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("RGB color");
        setPreferredSize(new java.awt.Dimension(550, 500));
        setVisible(true);

        panel1.setBackground(new java.awt.Color(0, 0, 0));

        panel1r.setColumns(3);
        panel1r.setForeground(new java.awt.Color(255, 0, 0));
        panel1r.setText("0");
        panel1r.setToolTipText("");
        panel1r.setAutoscrolls(false);
        panel1r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panel1rActionPerformed(evt);
            }
        });

        panel_txt1.setForeground(new java.awt.Color(153, 153, 153));
        panel_txt1.setText("Panel 1");

        panelg1.setColumns(3);
        panelg1.setForeground(new java.awt.Color(0, 255, 0));
        panelg1.setText("0");
        panelg1.setToolTipText("");
        panelg1.setAutoscrolls(false);

        panelb1.setColumns(3);
        panelb1.setForeground(new java.awt.Color(0, 0, 255));
        panelb1.setText("0");
        panelb1.setToolTipText("");
        panelb1.setAutoscrolls(false);
        panelb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelb1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_txt1)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(panel1r, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelg1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelb1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_txt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(panel1r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        panel2.setBackground(new java.awt.Color(0, 0, 0));

        panel2r.setColumns(3);
        panel2r.setForeground(new java.awt.Color(255, 0, 0));
        panel2r.setText("0");
        panel2r.setToolTipText("");
        panel2r.setAutoscrolls(false);

        panel_txt2.setForeground(new java.awt.Color(153, 153, 153));
        panel_txt2.setText("Panel 2");

        panelg2.setColumns(3);
        panelg2.setForeground(new java.awt.Color(0, 255, 0));
        panelg2.setText("0");
        panelg2.setToolTipText("");
        panelg2.setAutoscrolls(false);

        panelb2.setColumns(3);
        panelb2.setForeground(new java.awt.Color(0, 0, 255));
        panelb2.setText("0");
        panelb2.setToolTipText("");
        panelb2.setAutoscrolls(false);
        panelb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelb2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_txt2)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(panel2r, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelg2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelb2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_txt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(panel2r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        center_panel.setBackground(new java.awt.Color(204, 204, 204));
        center_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        status.setEditable(false);
        status.setBackground(new java.awt.Color(204, 204, 204));
        status.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        status.setForeground(new java.awt.Color(255, 0, 51));
        status.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        status.setText("Good");

        status_txt.setForeground(new java.awt.Color(255, 0, 51));
        status_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status_txt.setText("Status");

        javax.swing.GroupLayout center_panelLayout = new javax.swing.GroupLayout(center_panel);
        center_panel.setLayout(center_panelLayout);
        center_panelLayout.setHorizontalGroup(
            center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
            .addComponent(status_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        center_panelLayout.setVerticalGroup(
            center_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(center_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(status_txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );

        button_panel.setBackground(new java.awt.Color(0, 128, 128));

        format1_button.setText("Format");
        format1_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                format1_buttonActionPerformed(evt);
            }
        });

        default_button.setText("Default");
        default_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                default_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout button_panelLayout = new javax.swing.GroupLayout(button_panel);
        button_panel.setLayout(button_panelLayout);
        button_panelLayout.setHorizontalGroup(
            button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(format1_button)
                .addGap(91, 91, 91)
                .addComponent(default_button)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        button_panelLayout.setVerticalGroup(
            button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_panelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(format1_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(default_button))
                .addContainerGap())
        );

        panel_reserve.setBackground(new java.awt.Color(0, 128, 128));

        panel4.setBackground(new java.awt.Color(0, 0, 0));

        panel4r.setColumns(3);
        panel4r.setForeground(new java.awt.Color(255, 0, 0));
        panel4r.setText("0");
        panel4r.setToolTipText("");
        panel4r.setAutoscrolls(false);

        panel_txt4.setForeground(new java.awt.Color(153, 153, 153));
        panel_txt4.setText("Panel 3");

        panelg4.setColumns(3);
        panelg4.setForeground(new java.awt.Color(0, 255, 0));
        panelg4.setText("0");
        panelg4.setToolTipText("");
        panelg4.setAutoscrolls(false);

        panelb4.setColumns(3);
        panelb4.setForeground(new java.awt.Color(0, 0, 255));
        panelb4.setText("0");
        panelb4.setToolTipText("");
        panelb4.setAutoscrolls(false);
        panelb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelb4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addComponent(panel4r, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelg4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel_txt4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelb4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_txt4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(panel4r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelg4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        panel5.setBackground(new java.awt.Color(0, 0, 0));

        panel5r.setColumns(3);
        panel5r.setForeground(new java.awt.Color(255, 0, 0));
        panel5r.setText("0");
        panel5r.setToolTipText("");
        panel5r.setAutoscrolls(false);

        panel_txt5.setForeground(new java.awt.Color(153, 153, 153));
        panel_txt5.setText("Panel 4");

        panelg5.setColumns(3);
        panelg5.setForeground(new java.awt.Color(0, 255, 0));
        panelg5.setText("0");
        panelg5.setToolTipText("");
        panelg5.setAutoscrolls(false);

        panelb5.setColumns(3);
        panelb5.setForeground(new java.awt.Color(0, 0, 255));
        panelb5.setText("0");
        panelb5.setToolTipText("");
        panelb5.setAutoscrolls(false);
        panelb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelb5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel5Layout.createSequentialGroup()
                        .addComponent(panel5r, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelg5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel_txt5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelb5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_txt5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(panel5r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelg5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelb5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        panel7.setBackground(new java.awt.Color(0, 0, 0));

        panel7r.setColumns(3);
        panel7r.setForeground(new java.awt.Color(255, 0, 0));
        panel7r.setText("0");
        panel7r.setToolTipText("");
        panel7r.setAutoscrolls(false);

        panel_txt7.setForeground(new java.awt.Color(153, 153, 153));
        panel_txt7.setText("Panel 6");

        panelg7.setColumns(3);
        panelg7.setForeground(new java.awt.Color(0, 255, 0));
        panelg7.setText("0");
        panelg7.setToolTipText("");
        panelg7.setAutoscrolls(false);

        panelb7.setColumns(3);
        panelb7.setForeground(new java.awt.Color(0, 0, 255));
        panelb7.setText("0");
        panelb7.setToolTipText("");
        panelb7.setAutoscrolls(false);
        panelb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelb7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel7Layout = new javax.swing.GroupLayout(panel7);
        panel7.setLayout(panel7Layout);
        panel7Layout.setHorizontalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel7Layout.createSequentialGroup()
                        .addComponent(panel7r, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelg7, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                    .addGroup(panel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panel_txt7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelb7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        panel7Layout.setVerticalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_txt7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(panel7r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelg7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelb7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        panel8.setBackground(new java.awt.Color(0, 0, 0));

        panel8r.setColumns(3);
        panel8r.setForeground(new java.awt.Color(255, 0, 0));
        panel8r.setText("0");
        panel8r.setToolTipText("");
        panel8r.setAutoscrolls(false);

        panel_txt8.setForeground(new java.awt.Color(153, 153, 153));
        panel_txt8.setText("Panel 7");

        panelg8.setColumns(3);
        panelg8.setForeground(new java.awt.Color(0, 255, 0));
        panelg8.setText("0");
        panelg8.setToolTipText("");
        panelg8.setAutoscrolls(false);

        panelb8.setColumns(3);
        panelb8.setForeground(new java.awt.Color(0, 0, 255));
        panelb8.setText("0");
        panelb8.setToolTipText("");
        panelb8.setAutoscrolls(false);
        panelb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelb8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel8Layout = new javax.swing.GroupLayout(panel8);
        panel8.setLayout(panel8Layout);
        panel8Layout.setHorizontalGroup(
            panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel8Layout.createSequentialGroup()
                        .addComponent(panel8r, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelg8, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                    .addGroup(panel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panel_txt8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelb8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel8Layout.setVerticalGroup(
            panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_txt8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(panel8r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelg8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelb8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout panel_reserveLayout = new javax.swing.GroupLayout(panel_reserve);
        panel_reserve.setLayout(panel_reserveLayout);
        panel_reserveLayout.setHorizontalGroup(
            panel_reserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_reserveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_reserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_reserveLayout.createSequentialGroup()
                        .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_reserveLayout.createSequentialGroup()
                        .addComponent(panel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        panel_reserveLayout.setVerticalGroup(
            panel_reserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_reserveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_reserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(panel_reserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_reserve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(center_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_reserve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(center_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(button_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panel1rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panel1rActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panel1rActionPerformed

    private void panelb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelb1ActionPerformed

    private void panelb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelb2ActionPerformed

    private void panelb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelb4ActionPerformed

    private void panelb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelb5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelb5ActionPerformed

    private void panelb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelb7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelb7ActionPerformed

    private void panelb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelb8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelb8ActionPerformed

    private void format1_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_format1_buttonActionPerformed
       
       try
       {panel1.setBackground(new Color(Integer.parseInt(panel1r.getText()),Integer.parseInt(panelb1.getText()),Integer.parseInt(panelg1.getText())));
       panel2.setBackground(new Color(Integer.parseInt(panel2r.getText()),Integer.parseInt(panelb2.getText()),Integer.parseInt(panelg2.getText())));
       panel4.setBackground(new Color(Integer.parseInt(panel4r.getText()),Integer.parseInt(panelb4.getText()),Integer.parseInt(panelg4.getText())));
       panel5.setBackground(new Color(Integer.parseInt(panel5r.getText()),Integer.parseInt(panelb5.getText()),Integer.parseInt(panelg5.getText())));
       panel7.setBackground(new Color(Integer.parseInt(panel7r.getText()),Integer.parseInt(panelb7.getText()),Integer.parseInt(panelg7.getText())));
       panel8.setBackground(new Color(Integer.parseInt(panel8r.getText()),Integer.parseInt(panelb8.getText()),Integer.parseInt(panelg8.getText())));
       
       
       
       
        this.getContentPane().setLayout(lay1);
                panel_reserve.setLayout(lay2);

        

        this.revalidate();
        this.pack();
        this.repaint();
        
       status.setText("Good");
       }
       catch(Exception ex)
       {
           status.setText("Error! Check Values");
       }
       
       
    }//GEN-LAST:event_format1_buttonActionPerformed

    private void default_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_default_buttonActionPerformed
        this.getContentPane().setLayout(lm);
        panel_reserve.setLayout(lm2);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_default_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel button_panel;
    private javax.swing.JPanel center_panel;
    private javax.swing.JButton default_button;
    private javax.swing.JButton format1_button;
    private javax.swing.JPanel panel1;
    private javax.swing.JTextField panel1r;
    private javax.swing.JPanel panel2;
    private javax.swing.JTextField panel2r;
    private javax.swing.JPanel panel4;
    private javax.swing.JTextField panel4r;
    private javax.swing.JPanel panel5;
    private javax.swing.JTextField panel5r;
    private javax.swing.JPanel panel7;
    private javax.swing.JTextField panel7r;
    private javax.swing.JPanel panel8;
    private javax.swing.JTextField panel8r;
    private javax.swing.JPanel panel_reserve;
    private javax.swing.JLabel panel_txt1;
    private javax.swing.JLabel panel_txt2;
    private javax.swing.JLabel panel_txt4;
    private javax.swing.JLabel panel_txt5;
    private javax.swing.JLabel panel_txt7;
    private javax.swing.JLabel panel_txt8;
    private javax.swing.JTextField panelb1;
    private javax.swing.JTextField panelb2;
    private javax.swing.JTextField panelb4;
    private javax.swing.JTextField panelb5;
    private javax.swing.JTextField panelb7;
    private javax.swing.JTextField panelb8;
    private javax.swing.JTextField panelg1;
    private javax.swing.JTextField panelg2;
    private javax.swing.JTextField panelg4;
    private javax.swing.JTextField panelg5;
    private javax.swing.JTextField panelg7;
    private javax.swing.JTextField panelg8;
    private javax.swing.JTextField status;
    private javax.swing.JLabel status_txt;
    // End of variables declaration//GEN-END:variables
}
